name: Release

on: workflow_dispatch

jobs:
  ungoogled-chromium-debian-release:
    name: Release new ungoogled-chromium package for Debian
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Convert from shallow repository to full repository
        run: git fetch --unshallow
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Install extra packages
        run: sudo apt install -y xmlstarlet
      - name: Run release script
        #env:
        #  OBS_API_USERNAME: ${{ secrets.OBS_API_USERNAME }}
        #  OBS_API_PASSWORD: ${{ secrets.OBS_API_PASSWORD }}
        #  OBS_API_PROJECT: ${{ secrets.OBS_API_PROJECT }}
        run: .github/workflows/release.sh
